-- MySQL Script generated by MySQL Workbench
-- Wed Dec  9 12:45:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Auto_Ecole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auto_Ecole` (
  `idAuto_Ecole` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `logo` BLOB NULL,
  `adresse_postale` VARCHAR(200) NOT NULL,
  `adresse_mail` VARCHAR(100) NOT NULL,
  `numero_de_telephone` INT NOT NULL,
  `Presentation` VARCHAR(300) NULL,
  PRIMARY KEY (`idAuto_Ecole`),
  UNIQUE INDEX `idAuto_Ecole_UNIQUE` (`idAuto_Ecole` ASC),
  UNIQUE INDEX `numero_de_telephone_UNIQUE` (`numero_de_telephone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personne` (
  `idPersonne` INT NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `date_de_naissance` DATE NOT NULL,
  `adresse_mail` VARCHAR(100) NOT NULL,
  `mot_de_passe` VARCHAR(100) NOT NULL,
  `image` BLOB NULL,
  `cle_etrangere_autoecole` INT NULL,
  PRIMARY KEY (`idPersonne`),
  UNIQUE INDEX `idPersonne_UNIQUE` (`idPersonne` ASC),
  INDEX `fk_Personne_Auto_Ecole1_idx` (`cle_etrangere_autoecole` ASC),
  CONSTRAINT `fk_Personne_Auto_Ecole1`
    FOREIGN KEY (`cle_etrangere_autoecole`)
    REFERENCES `mydb`.`Auto_Ecole` (`idAuto_Ecole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `idTest` INT NOT NULL,
  `nom_du_test` VARCHAR(100) NOT NULL,
  `periode` TIMESTAMP(6) NOT NULL,
  `cle_etrangere_personne` INT NULL,
  PRIMARY KEY (`idTest`),
  UNIQUE INDEX `idTest_UNIQUE` (`idTest` ASC),
  INDEX `fk_Test_Personne1_idx` (`cle_etrangere_personne` ASC),
  CONSTRAINT `fk_Test_Personne1`
    FOREIGN KEY (`cle_etrangere_personne`)
    REFERENCES `mydb`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Capteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capteurs` (
  `idCapteurs` INT NOT NULL,
  `nom_du_capteur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCapteurs`),
  UNIQUE INDEX `idCapteurs_UNIQUE` (`idCapteurs` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Résultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Résultats` (
  `idRésultats` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `mesure_de_donnee` DECIMAL(10) ZEROFILL NULL,
  `Test_idTest` INT NOT NULL,
  `Test_Personne_idPersonne` INT NOT NULL,
  `Capteurs_idCapteurs` INT NOT NULL,
  UNIQUE INDEX `idRésultats_UNIQUE` (`idRésultats` ASC),
  PRIMARY KEY (`idRésultats`, `Test_idTest`, `Test_Personne_idPersonne`, `Capteurs_idCapteurs`),
  INDEX `fk_Résultats_Test1_idx` (`Test_idTest` ASC, `Test_Personne_idPersonne` ASC),
  INDEX `fk_Résultats_Capteurs1_idx` (`Capteurs_idCapteurs` ASC),
  CONSTRAINT `fk_Résultats_Test1`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Résultats_Capteurs1`
    FOREIGN KEY (`Capteurs_idCapteurs`)
    REFERENCES `mydb`.`Capteurs` (`idCapteurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ Reponse` (
  `idReponse` INT NOT NULL,
  `reponse` VARCHAR(300) NULL,
  PRIMARY KEY (`idReponse`),
  UNIQUE INDEX `idReponse_UNIQUE` (`idReponse` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FAQ Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FAQ Question` (
  `idQuestion` INT NOT NULL,
  `type_de_question` VARCHAR(100) NULL,
  `question` VARCHAR(200) NULL,
  `FAQ Reponse_idReponse` INT NOT NULL,
  PRIMARY KEY (`idQuestion`, `FAQ Reponse_idReponse`),
  UNIQUE INDEX `idFAQ Question_UNIQUE` (`idQuestion` ASC),
  INDEX `fk_FAQ Question_FAQ Reponse1_idx` (`FAQ Reponse_idReponse` ASC),
  CONSTRAINT `fk_FAQ Question_FAQ Reponse1`
    FOREIGN KEY (`FAQ Reponse_idReponse`)
    REFERENCES `mydb`.`FAQ Reponse` (`idReponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
